version: '3.8'
services:
  db:
    image: postgres:alpine3.18
    restart: always
    environment:
      POSTGRES_USER: lorenzo
      POSTGRES_PASSWORD: L0renz0
    ports:
      - 5434:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
